### PR TITLE
feat: Add a toggle to the `Hide launch icon` menu

### PR DESCRIPTION
**Pull request by rufusin**

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
Thanks for the PR but it does not follow the contribution instructions in the README

**Comment by kazimmt** [comment]
Maybe create the same PR in https://github.com/microg/GmsCore

If they merge it, we will have it in ReVanced GmsCore too

**Comment by ILoveOpenSourceApplications** [comment]
> Maybe create the same PR in https://github.com/microg/GmsCore
> 
> If they merge it, we will have it in ReVanced GmsCore too.

Well after seeing this and having not seen @rufusin around, I took matters into my own hands and opened https://github.com/microg/GmsCore/pull/2462. Hoping there'll be some minute changes as the code worked pretty well. But I was wrong and some of the recent review requests are outside of my understanding. So if anyone here is knowledgeable in this area and have some free time and want to see this implemented, do feel to help me in whatever way you can.

**Comment by kazimmt** [comment]
@YT-Advanced maybe you can help him

**Pull request closed without merging**
